% MESH
%
% Files
%   auxstructure      - auxiliary structure for a 2-D triangulation.
%   auxstructure3     - auxiliary structure for a 3-D triangulation.
%   auxstructurec     - auxiliary structure for a 2-D triangulation (C-code).
%   bdsmoothing       - improves the boundary of a triangular mesh
%   circlemesh        - generates a mesh for a circle
%   circumcenter      - computes circumcenters of a triangulation
%   cleanup           - delete isolated vertices.
%   coloring          - color vertices of a graph
%   cubemesh          - a uniform mesh of a cube
%   cvtuniformmesh    - n is the number of intervales in one coordinate direction
%   distmeshsmoothing - mesh smoothing using distmesh
%   edgeswap          - swap edges
%   findboundary      - finds the boundary of a triangulation
%   findboundary3     - find boundary faces and nodes
%   findquadboundary  - finds the boundary of a quad mesh
%   fixorder          - set all triangles counter-clockwise
%   fixorder3         - fix orientation of tetrahedron 
%   fixorientation    - set all triangles counter-clockwise
%   flowpastcylinder  - Generate a rectangular mesh with a circular hole
%   initmesh          - initialize a triangulation
%   label             - label the refinement edge of a 2-D triangulation
%   label3            - label the refinement edge of a 3-D triangulation
%   meshquality       - computes qualities of a mesh
%   meshsmoothing     - improves the geometric mesh quality
%   odtmesh2d         - mesh generator based on Optimal Delaunay Triangulation
%   odtmeshdemo2d     - demo of 2-D mesh generated by odtmesh
%   odtmeshopt        - mesh optimization based on ODT 
%   optmesh           - optimize the input mesh
%   perturbmesh       - perturb all the interior nodes with the local size.
%   quadauxstructure  - AUXSTRUCTURE auxiliary structure for a 2-D quad mesh
%   reftet            - 
%   rmisopoint        - remove isolate points 
%   shishkinmesh      - layer-adapted piecewise uniform mesh
%   simplexvolume     - Simplex volume
%   simpqual          - Simplex quality.
%   squaremesh        - uniform mesh of a square
%   squaremeshp       - uniform mesh of a square with periodic condition
%   uniformity        - Copyright (C) 2004-2006 Per-Olof Persson. See COPYRIGHT.TXT for details.
